# Generated by Django 5.2.10 on 2026-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "average_buy_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "portfolios",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "previous_close",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "day_high",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "day_low",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("volume", models.BigIntegerField(default=0)),
                ("market_cap", models.BigIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stocks",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="StockPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "stock_price_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("shares", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "price_per_share",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "watchlists",
            },
        ),
    ]
